name: Unzip Project

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: unzip -o GrayTrackAndroid.zip
      - run: rm -f GrayTrackAndroid.zip
      - run: |
          git config user.name "moknethunter"
          git config user.email "moknethunter@github.com"
          git add .
          git commit -m "unzip ready" || true
          git push
